linter:
  rules:
    # - prefer_relative_imports
    # - prefer_const_constructors
    # - directives_ordering
    # - avoid_relative_lib_imports
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - constant_identifier_names
    - non_constant_identifier_names
    - empty_statements
    - curly_braces_in_flow_control_structures
    - implementation_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catching_errors
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - one_member_abstracts
    - prefer_mixin
    - prefer_final_fields
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null
    - avoid_returning_this
    - omit_local_variable_types
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - hash_and_equals
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_null_checks_in_equality_operators
