name: flute
description: A weird flutter package that has some extensions and local storage.
version: 1.0.5
homepage: https://github.com/ragokan/flute
repository: https://github.com/ragokan/flute

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
