name: flute
description: An amazing flutter package that I created for myself.
version: 1.0.7
homepage: https://github.com/ragokan/flute
repository: https://github.com/ragokan/flute

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.10
  flutter_riverpod: ^1.0.4
  dio: ^4.0.6
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
