name: flute
description: An amazing flutter package that I created for myself.
version: 1.0.9
homepage: https://github.com/ragokan/flute
repository: https://github.com/ragokan/flute

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  dio: ^5.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverbloc: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
